# Default values for chat.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: "production"
replicaCount: 1

imagePullSecret:
  enabled: false
  name: ""

chat_backend:
  secret_name: ""
  service_account: default

  image:
    repository: tlmcleanlab.azurecr.io/tlm/chat-backend
    pullPolicy: IfNotPresent

  container:
    port: 80

  service:
    type: ClusterIP
    port: 8080

  resources:
    limits:
      cpu: 512m
      memory: 1024Mi
    requests:
      cpu: 512m
      memory: 1024Mi

  num_proxies: 0

  # Environment variables to set on the container
  # e.g: TLM_DEFAULT_MODEL_API_BASE=https://<your-resource-name>.openai.azure.com/
  defaults: {}
