apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-chat-backend
  labels:
    {{- include "tlm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.chat_backend.service.type }}
  ports:
    - port: {{ .Values.chat_backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tlm.selectorLabels" . | nindent 4 }}
